package com.lovelycatv.crystalframework.approval.repository

import com.lovelycatv.crystalframework.approval.entity.ApprovalFlowDefinitionEntity
import com.lovelycatv.crystalframework.shared.repository.BaseRepository

interface ApprovalFlowDefinitionRepository : BaseRepository<ApprovalFlowDefinitionEntity>
