spring:
  application:
    name: springboot-template
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    pool:
      initial-size: 20
      max-size: 40
      max-idle-time: 30m
#      validation-query: SELECT 1
    properties:
      preferQueryMode: simple
      autocommit: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: login
          google:
            user-name-attribute: name
          oicq:
            authorization-uri: https://graph.qq.com/oauth2.0/authorize
            token-uri: https://graph.qq.com/oauth2.0/token
            user-info-uri: https://graph.qq.com/user/get_user_info
        registration:
          github:
            provider: github
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: ${OAUTH_GITHUB_REDIRECT_URL}
            authorization-grant-type: authorization_code
          oicq:
            provider: oicq
            client-id: ${OAUTH_OICQ_CLIENT_ID}
            client-secret: ${OAUTH_OICQ_CLIENT_SECRET}
            scope: get_user_info
            redirect-uri: ${OAUTH_OICQ_REDIRECT_URL}
            authorization-grant-type: authorization_code
          google:
            provider: google
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URL}
            authorization-grant-type: authorization_code

  http:
    codecs:
      max-in-memory-size: 10MB
  webflux:
    multipart:
      max-in-memory-size: 10MB
  reactor:
    debug-agent:
      enabled: true
crystalframework:
  resource:
    avatar:
      supported-content-types:
        - image/png
        - image/jpeg
        - image/webp
    tenant-icon:
      supported-content-types:
        - image/png
        - image/jpeg
        - image/webp

logging:
  level:
    root: info
    org.springframework.security: info
    org.springframework.web: info
    org.springframework.transaction: info
    org.springframework.r2dbc: info
    io.r2dbc.postgresql: info
    org.springframework.boot.actuate: info
    com.lovelycatv.crystalframework.shared.exception: debug
server:
  reactive:
    session:
      cookie:
        secure: true
        path: /
        http-only: true
        same-site: none
        domain: ${COOKIE_DOMAIN}
  forward-headers-strategy: framework
  port: ${BACKEND_PORT}