spring:
  application:
    name: springboot-template
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    pool:
      initial-size: 20
      max-size: 40
      max-idle-time: 30m
#      validation-query: SELECT 1
    properties:
      preferQueryMode: simple
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: login
        registration:
          github:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            scope: read:user
  http:
    codecs:
      max-in-memory-size: 10MB
  webflux:
    multipart:
      max-in-memory-size: 10MB

crystalframework:
  resource:
    avatar:
      supported-content-types:
        - image/png
        - image/jpeg
        - image/webp

logging:
  level:
    root: info
    org.springframework.security: info
    org.springframework.web: info
    org.springframework.r2dbc: info
    org.springframework.boot.actuate: info