-- Update permission descriptions to short English texts (canonical DB values).
-- Previously descriptions defaulted to `name`, which conflicted with the new
-- frontend i18n mapping flow. RbacTableDataCheckRunner never updates existing
-- rows, so the values below are written directly here.

UPDATE public.user_permissions p
SET description = v.description
FROM (VALUES
    -- Menus
    ('permission', 'Manage user permissions menu'),
    ('role', 'Manage user roles menu'),
    ('user', 'Manage users menu'),
    ('user.role', 'Manage user-role assignments menu'),
    ('settings', 'Access system settings menu'),
    ('oauth.account', 'Manage OAuth accounts menu'),
    ('file.resource', 'Manage file resources menu'),
    ('storage.provider', 'Manage storage providers menu'),
    ('mail.template.category', 'Manage mail template categories menu'),
    ('mail.template.type', 'Manage mail template types menu'),
    ('mail.template', 'Manage mail templates menu'),
    ('tenant', 'Manage tenants menu'),
    ('tenant.tire.type', 'Manage tenant tire types menu'),
    ('tenant.tire.benefit.feature', 'Manage tenant tire benefit features menu'),
    ('tenant.tire.benefit.value', 'Manage tenant tire benefit values menu'),
    ('tenant.department', 'Manage tenant departments menu'),
    ('tenant.role', 'Manage tenant roles menu'),
    ('tenant.permission', 'Manage tenant permissions menu'),
    ('tenant.member', 'Manage tenant members menu'),
    ('tenant.department.member', 'Manage tenant department members menu'),
    ('tenant.member.role', 'Manage tenant member roles menu'),
    ('tenant.role.permission', 'Manage tenant role permissions menu'),
    ('tenant.invitation', 'Manage tenant invitations menu'),
    ('tenant.message.channel', 'Manage tenant message channels menu'),
    ('system.message.channel', 'Manage system message channels menu'),
    ('audit.log', 'Manage audit logs menu'),
    ('mail.send.log', 'Manage mail send logs menu'),
    ('user.login.log', 'Manage user login logs menu'),
    ('monitor.sessions', 'Manage active sessions menu'),
    ('announcement', 'Manage announcements menu'),
    ('approval.flow.definition', 'Manage approval flow definitions menu'),
    ('tenant.approval.flow.definition', 'Manage tenant approval flow definitions menu'),
    ('approval.flow.instance', 'Manage approval flow instances menu'),
    ('tenant.approval.flow.instance', 'Manage tenant approval flow instances menu'),
    ('system.dict.type', 'Manage system dictionary types menu'),
    ('system.dict.item', 'Manage system dictionary items menu'),
    ('tenant.dict.type', 'Manage tenant dictionary types menu'),
    ('tenant.dict.item', 'Manage tenant dictionary items menu'),
    -- Components
    ('dashboard.business.statistics', 'Dashboard business statistics widget'),
    ('dashboard.system.metrics', 'Dashboard system metrics widget'),
    ('dashboard.tenant.joined', 'Dashboard joined tenants widget'),
    ('dashboard.announcements', 'Dashboard announcements widget'),
    -- Actions - user permission / role / user
    ('permission.create', 'Create user permissions'),
    ('permission.read', 'Read user permissions'),
    ('permission.update', 'Update user permissions'),
    ('permission.delete', 'Delete user permissions'),
    ('role.create', 'Create user roles'),
    ('role.read', 'Read user roles'),
    ('role.update', 'Update user roles'),
    ('role.delete', 'Delete user roles'),
    ('user.create', 'Create users'),
    ('user.read', 'Read users'),
    ('user.update', 'Update users'),
    ('user.delete', 'Delete users'),
    ('role.permission.read', 'Read role permission assignments'),
    ('role.permission.update', 'Update role permission assignments'),
    ('user.role.read', 'Read user role assignments'),
    ('user.role.update', 'Update user role assignments'),
    -- Actions - system settings / maintenance
    ('settings.read', 'Read system settings'),
    ('settings.update', 'Update system settings'),
    ('settings.test.sendEmail', 'Send test email via system settings'),
    ('settings.test.sendMessage', 'Send test message via system settings'),
    ('maintenance.access', 'Access maintenance operations'),
    ('maintenance.update', 'Update maintenance operations'),
    -- Actions - oauth account
    ('oauth.account.create', 'Create OAuth accounts'),
    ('oauth.account.read', 'Read OAuth accounts'),
    ('oauth.account.update', 'Update OAuth accounts'),
    ('oauth.account.delete', 'Delete OAuth accounts'),
    -- Actions - file resource / storage provider
    ('file.resource.create', 'Create file resources'),
    ('file.resource.read', 'Read file resources'),
    ('file.resource.update', 'Update file resources'),
    ('file.resource.delete', 'Delete file resources'),
    ('storage.provider.create', 'Create storage providers'),
    ('storage.provider.read', 'Read storage providers'),
    ('storage.provider.update', 'Update storage providers'),
    ('storage.provider.delete', 'Delete storage providers'),
    -- Actions - mail template
    ('mail.template.category.create', 'Create mail template categories'),
    ('mail.template.category.read', 'Read mail template categories'),
    ('mail.template.category.update', 'Update mail template categories'),
    ('mail.template.category.delete', 'Delete mail template categories'),
    ('mail.template.type.create', 'Create mail template types'),
    ('mail.template.type.read', 'Read mail template types'),
    ('mail.template.type.update', 'Update mail template types'),
    ('mail.template.type.delete', 'Delete mail template types'),
    ('mail.template.create', 'Create mail templates'),
    ('mail.template.read', 'Read mail templates'),
    ('mail.template.update', 'Update mail templates'),
    ('mail.template.delete', 'Delete mail templates'),
    -- Actions - tenant top-level
    ('tenant.create', 'Create tenants'),
    ('tenant.read', 'Read tenants'),
    ('tenant.update', 'Update tenants'),
    ('tenant.delete', 'Delete tenants'),
    -- Actions - tenant tire type / benefit
    ('tenant.tire.type.create', 'Create tenant tire types'),
    ('tenant.tire.type.read', 'Read tenant tire types'),
    ('tenant.tire.type.update', 'Update tenant tire types'),
    ('tenant.tire.type.delete', 'Delete tenant tire types'),
    ('tenant.tire.benefit.feature.create', 'Create tenant tire benefit features'),
    ('tenant.tire.benefit.feature.read', 'Read tenant tire benefit features'),
    ('tenant.tire.benefit.feature.update', 'Update tenant tire benefit features'),
    ('tenant.tire.benefit.feature.delete', 'Delete tenant tire benefit features'),
    ('tenant.tire.benefit.value.create', 'Create tenant tire benefit values'),
    ('tenant.tire.benefit.value.read', 'Read tenant tire benefit values'),
    ('tenant.tire.benefit.value.update', 'Update tenant tire benefit values'),
    ('tenant.tire.benefit.value.delete', 'Delete tenant tire benefit values'),
    -- Actions - tenant admin scope
    ('tenant.department.create', 'Create tenant departments across tenants'),
    ('tenant.department.read', 'Read tenant departments across tenants'),
    ('tenant.department.update', 'Update tenant departments across tenants'),
    ('tenant.department.delete', 'Delete tenant departments across tenants'),
    ('tenant.role.create', 'Create tenant roles across tenants'),
    ('tenant.role.read', 'Read tenant roles across tenants'),
    ('tenant.role.update', 'Update tenant roles across tenants'),
    ('tenant.role.delete', 'Delete tenant roles across tenants'),
    ('tenant.permission.create', 'Create tenant permissions across tenants'),
    ('tenant.permission.read', 'Read tenant permissions across tenants'),
    ('tenant.permission.update', 'Update tenant permissions across tenants'),
    ('tenant.permission.delete', 'Delete tenant permissions across tenants'),
    ('tenant.member.create', 'Create tenant members across tenants'),
    ('tenant.member.read', 'Read tenant members across tenants'),
    ('tenant.member.update', 'Update tenant members across tenants'),
    ('tenant.member.delete', 'Delete tenant members across tenants'),
    ('tenant.department.member.create', 'Assign tenant department members across tenants'),
    ('tenant.department.member.read', 'Read tenant department members across tenants'),
    ('tenant.department.member.update', 'Update tenant department members across tenants'),
    ('tenant.department.member.delete', 'Remove tenant department members across tenants'),
    ('tenant.member.role.read', 'Read tenant member role assignments across tenants'),
    ('tenant.member.role.update', 'Update tenant member role assignments across tenants'),
    ('tenant.role.permission.read', 'Read tenant role permission assignments across tenants'),
    ('tenant.role.permission.update', 'Update tenant role permission assignments across tenants'),
    ('tenant.invitation.create', 'Create tenant invitations across tenants'),
    ('tenant.invitation.read', 'Read tenant invitations across tenants'),
    ('tenant.invitation.update', 'Update tenant invitations across tenants'),
    ('tenant.invitation.delete', 'Delete tenant invitations across tenants'),
    -- Actions - message channel
    ('tenant.message.channel.create', 'Create tenant-scope message channels across tenants'),
    ('tenant.message.channel.read', 'Read tenant-scope message channels across tenants'),
    ('tenant.message.channel.update', 'Update tenant-scope message channels across tenants'),
    ('tenant.message.channel.delete', 'Delete tenant-scope message channels across tenants'),
    ('system.message.channel.create', 'Create system-scope message channels'),
    ('system.message.channel.read', 'Read system-scope message channels'),
    ('system.message.channel.update', 'Update system-scope message channels'),
    ('system.message.channel.delete', 'Delete system-scope message channels'),
    ('message.channel.create', 'Create message channels in any scope'),
    ('message.channel.read', 'Read message channels in any scope'),
    ('message.channel.update', 'Update message channels in any scope'),
    ('message.channel.delete', 'Delete message channels in any scope'),
    -- Actions - logs
    ('audit.log.create', 'Create audit logs'),
    ('audit.log.read', 'Read audit logs'),
    ('audit.log.update', 'Update audit logs'),
    ('audit.log.delete', 'Delete audit logs'),
    ('mail.send.log.read', 'Read mail send logs'),
    ('user.login.log.read', 'Read user login logs'),
    -- Actions - dashboard / monitor
    ('dashboard.business.statistics.read', 'Read dashboard business statistics'),
    ('dashboard.system.metrics.read', 'Read dashboard system metrics'),
    ('monitor.sessions.read', 'Read active session monitor data'),
    -- Actions - announcement
    ('announcement.create', 'Create announcements'),
    ('announcement.read', 'Read announcements'),
    ('announcement.update', 'Update announcements'),
    ('announcement.delete', 'Delete announcements'),
    ('announcement.list', 'List published announcements'),
    -- Actions - approval flow definition
    ('approval.flow.definition.create', 'Create approval flow definitions in any scope'),
    ('approval.flow.definition.read', 'Read approval flow definitions in any scope'),
    ('approval.flow.definition.update', 'Update approval flow definitions in any scope'),
    ('approval.flow.definition.delete', 'Delete approval flow definitions in any scope'),
    ('system.approval.flow.definition.create', 'Create system-scope approval flow definitions'),
    ('system.approval.flow.definition.read', 'Read system-scope approval flow definitions'),
    ('system.approval.flow.definition.update', 'Update system-scope approval flow definitions'),
    ('system.approval.flow.definition.delete', 'Delete system-scope approval flow definitions'),
    ('tenant.approval.flow.definition.create', 'Create tenant-scope approval flow definitions across tenants'),
    ('tenant.approval.flow.definition.read', 'Read tenant-scope approval flow definitions across tenants'),
    ('tenant.approval.flow.definition.update', 'Update tenant-scope approval flow definitions across tenants'),
    ('tenant.approval.flow.definition.delete', 'Delete tenant-scope approval flow definitions across tenants'),
    -- Actions - approval flow instance
    ('approval.flow.instance.read', 'Read approval flow instances in any scope'),
    ('tenant.approval.flow.instance.read', 'Read tenant-scope approval flow instances across tenants'),
    -- Actions - dictionary
    ('system.dict.type.create', 'Create system-scope dictionary types'),
    ('system.dict.type.read', 'Read system-scope dictionary types'),
    ('system.dict.type.update', 'Update system-scope dictionary types'),
    ('system.dict.type.delete', 'Delete system-scope dictionary types'),
    ('system.dict.item.create', 'Create system-scope dictionary items'),
    ('system.dict.item.read', 'Read system-scope dictionary items'),
    ('system.dict.item.update', 'Update system-scope dictionary items'),
    ('system.dict.item.delete', 'Delete system-scope dictionary items'),
    ('tenant.dict.type.create', 'Create tenant-scope dictionary types across tenants'),
    ('tenant.dict.type.read', 'Read tenant-scope dictionary types across tenants'),
    ('tenant.dict.type.update', 'Update tenant-scope dictionary types across tenants'),
    ('tenant.dict.type.delete', 'Delete tenant-scope dictionary types across tenants'),
    ('tenant.dict.item.create', 'Create tenant-scope dictionary items across tenants'),
    ('tenant.dict.item.read', 'Read tenant-scope dictionary items across tenants'),
    ('tenant.dict.item.update', 'Update tenant-scope dictionary items across tenants'),
    ('tenant.dict.item.delete', 'Delete tenant-scope dictionary items across tenants'),
    ('dict.type.create', 'Create dictionary types in any scope'),
    ('dict.type.read', 'Read dictionary types in any scope'),
    ('dict.type.update', 'Update dictionary types in any scope'),
    ('dict.type.delete', 'Delete dictionary types in any scope'),
    ('dict.item.create', 'Create dictionary items in any scope'),
    ('dict.item.read', 'Read dictionary items in any scope'),
    ('dict.item.update', 'Update dictionary items in any scope'),
    ('dict.item.delete', 'Delete dictionary items in any scope')
) AS v(name, description)
WHERE p.name = v.name;

UPDATE public.tenant_permissions p
SET description = v.description
FROM (VALUES
    -- Menus
    ('i.tenant.dashboard', 'My tenant dashboard menu'),
    ('i.tenant.profile', 'My tenant profile menu'),
    ('i.tenant.personal.profile', 'My personal tenant profile menu'),
    ('i.tenant.member', 'My tenant members menu'),
    ('i.tenant.invitation', 'My tenant invitations menu'),
    ('i.tenant.role', 'My tenant roles menu'),
    ('i.tenant.member.role', 'My tenant member roles menu'),
    ('i.tenant.department', 'My tenant departments menu'),
    ('i.tenant.message.channel', 'My tenant message channels menu'),
    ('i.tenant.dict.type', 'My tenant dictionary types menu'),
    ('i.tenant.dict.item', 'My tenant dictionary items menu'),
    ('i.tenant.approval.flow.definition', 'My tenant approval flow definitions menu'),
    ('i.tenant.approval.flow.instance', 'My tenant approval flow instances menu'),
    -- Actions - profile / oauth
    ('i.tenant.profile.read.basic', 'Read basic tenant profile'),
    ('i.tenant.profile.read', 'Read tenant profile'),
    ('i.tenant.profile.update', 'Update tenant profile'),
    ('i.tenant.personal.profile.oauth.read', 'Read own OAuth bindings'),
    ('i.tenant.personal.profile.oauth.bind', 'Bind an OAuth account'),
    ('i.tenant.personal.profile.oauth.unbind', 'Unbind an OAuth account'),
    -- Actions - member / invitation / role
    ('i.tenant.member.read', 'Read members within own tenant'),
    ('i.tenant.member.update', 'Update members within own tenant'),
    ('i.tenant.member.delete', 'Remove members from own tenant'),
    ('i.tenant.invitation.create', 'Create invitations for own tenant'),
    ('i.tenant.invitation.read', 'Read invitations of own tenant'),
    ('i.tenant.invitation.update', 'Update invitations of own tenant'),
    ('i.tenant.invitation.delete', 'Delete invitations of own tenant'),
    ('i.tenant.role.create', 'Create roles within own tenant'),
    ('i.tenant.role.read', 'Read roles within own tenant'),
    ('i.tenant.role.update', 'Update roles within own tenant'),
    ('i.tenant.role.delete', 'Delete roles within own tenant'),
    ('i.tenant.member.role.read', 'Read member role assignments within own tenant'),
    ('i.tenant.member.role.update', 'Update member role assignments within own tenant'),
    ('i.tenant.role.permission.read', 'Read role permission assignments within own tenant'),
    ('i.tenant.role.permission.update', 'Update role permission assignments within own tenant'),
    -- Actions - department / department member
    ('i.tenant.department.create', 'Create departments within own tenant'),
    ('i.tenant.department.read', 'Read departments within own tenant'),
    ('i.tenant.department.update', 'Update departments within own tenant'),
    ('i.tenant.department.delete', 'Delete departments within own tenant'),
    ('i.tenant.department.member.create', 'Assign members to departments within own tenant'),
    ('i.tenant.department.member.read', 'Read department members within own tenant'),
    ('i.tenant.department.member.update', 'Update department members within own tenant'),
    ('i.tenant.department.member.delete', 'Remove members from departments within own tenant'),
    -- Actions - mail / settings
    ('i.tenant.mail.member.join', 'Receive tenant member-join review emails'),
    ('i.tenant.settings.read', 'Read own tenant settings'),
    ('i.tenant.settings.update', 'Update own tenant settings'),
    -- Actions - message channel
    ('i.tenant.message.channel.create', 'Create message channels within own tenant'),
    ('i.tenant.message.channel.read', 'Read message channels within own tenant'),
    ('i.tenant.message.channel.update', 'Update message channels within own tenant'),
    ('i.tenant.message.channel.delete', 'Delete message channels within own tenant'),
    -- Actions - dictionary
    ('i.tenant.dict.type.create', 'Create dictionary types within own tenant'),
    ('i.tenant.dict.type.read', 'Read dictionary types within own tenant'),
    ('i.tenant.dict.type.update', 'Update dictionary types within own tenant'),
    ('i.tenant.dict.type.delete', 'Delete dictionary types within own tenant'),
    ('i.tenant.dict.item.create', 'Create dictionary items within own tenant'),
    ('i.tenant.dict.item.read', 'Read dictionary items within own tenant'),
    ('i.tenant.dict.item.update', 'Update dictionary items within own tenant'),
    ('i.tenant.dict.item.delete', 'Delete dictionary items within own tenant'),
    -- Actions - approval flow
    ('i.tenant.approval.flow.definition.create', 'Create approval flow definitions within own tenant'),
    ('i.tenant.approval.flow.definition.read', 'Read approval flow definitions within own tenant'),
    ('i.tenant.approval.flow.definition.update', 'Update approval flow definitions within own tenant'),
    ('i.tenant.approval.flow.definition.delete', 'Delete approval flow definitions within own tenant'),
    ('i.tenant.approval.flow.instance.read', 'Read approval flow instances within own tenant')
) AS v(name, description)
WHERE p.name = v.name;
