export const HEADER_API_ENCRYPTION_KEY = 'X-Secure-Key';
export const HEADER_API_AES_KEY = 'X-Secure-AES-Key';
export const RSA_PUBLIC_KEY_STORAGE_KEY = "RSA_PUBLIC_KEY";
export const RSA_PRIVATE_KEY_STORAGE_KEY = "RSA_PRIVATE_KEY";
export const AES_KEY_STORAGE_KEY = 'AES_SECRET_KEY';