package com.lovelycatv.crystalframework.shared.constants

object TableConstants {
    const val TABLE_USERS = "users"
    const val TABLE_TENANTS = "tenants"
    const val TABLE_TENANT_ROLES = "tenant_roles"
    const val TABLE_TENANT_PERMISSIONS = "tenant_permissions"
    const val TABLE_TENANT_ROLE_PERMISSION_RELATIONS = "tenant_role_permission_relations"
    const val TABLE_TENANT_MEMBERS = "tenant_members"
    const val TABLE_TENANT_MEMBER_ROLE_RELATIONS = "tenant_member_role_relations"
    const val TABLE_TENANT_DEPARTMENTS = "tenant_departments"
    const val TABLE_TENANT_DEPARTMENT_MEMBER_RELATIONS = "tenant_department_member_relations"
    const val TABLE_TENANT_INVITATIONS = "tenant_invitations"
    const val TABLE_TENANT_INVITATION_RECORDS = "tenant_invitation_records"
    const val TABLE_TENANT_TIRE_TYPES = "tenant_tire_types"
    const val TABLE_USER_ROLES = "user_roles"
    const val TABLE_USER_ROLE_RELATIONS = "user_role_relations"
    const val TABLE_USER_ROLE_PERMISSION_RELATIONS = "user_role_permission_relations"
    const val TABLE_USER_PERMISSIONS = "user_permissions"
    const val TABLE_OAUTH_ACCOUNTS = "oauth_accounts"
    const val TABLE_SYSTEM_SETTINGS = "system_settings"
    const val TABLE_AUDIT_MANAGER_LOGS = "audit_manager_logs"
    const val TABLE_MAIL_SEND_LOGS = "mail_send_logs"
    const val TABLE_MAIL_TEMPLATE_CATEGORIES = "mail_template_categories"
    const val TABLE_MAIL_TEMPLATE_TYPES = "mail_template_types"
    const val TABLE_MAIL_TEMPLATES = "mail_templates"
    const val TABLE_USER_LOGIN_LOGS = "user_login_logs"
    const val TABLE_FILE_RESOURCES = "file_resources"
    const val TABLE_STORAGE_PROVIDERS = "storage_providers"
}
