package com.lovelycatv.crystalframework.mail.service

import com.lovelycatv.crystalframework.mail.entity.MailTemplateCategoryEntity
import com.lovelycatv.crystalframework.mail.repository.MailTemplateCategoryRepository
import com.lovelycatv.crystalframework.shared.service.CachedBaseService

interface MailTemplateCategoryService : CachedBaseService<MailTemplateCategoryRepository, MailTemplateCategoryEntity>
