spring:
  application:
    name: springboot-template
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 5
      min-idle: 5
      max-size: 40
      max-idle-time: 30m
      max-acquire-time: 5s
      max-create-connection-time: 5s
      validation-query: SELECT 1
      validation-depth: REMOTE
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          min-idle: 12
          max-idle: 20
          max-active: 60
          max-wait: 3s
        shutdown-timeout: 100ms
      timeout: 5s
      connect-timeout: 3s
  security: {}

  http:
    codecs:
      max-in-memory-size: 10MB
  webflux:
    multipart:
      max-in-memory-size: 10MB
  reactor:
    debug-agent:
      enabled: true
  main:
    allow-circular-references: true
crystalframework:
  auth:
    jwt:
      expiration: 7d
  resource:
    avatar:
      supported-content-types:
        - image/png
        - image/jpeg
        - image/webp
    tenant-icon:
      supported-content-types:
        - image/png
        - image/jpeg
        - image/webp
  monitor:
    flush-interval-ms: 30000
  sharding:
    snowflake:
      start-point: 0
      timestamp-length: 41
      data-center-id-length: 5
      worker-id-length: 5
      sequence-id-length: 12
      gene-id-length: 0
      data-center-id: ${SNOWFLAKE_DATA_CENTER_ID:0}
      worker-id: ${SNOWFLAKE_WORKER_ID:0}
      actual-gene-length: 0
  test:
    smtp:
      subject: Crystal Framework SMTP Test
      content: This is a test email from Crystal Framework. If you received this message, your SMTP settings are working.
    message-channel:
      lark:
        default-message: 'hello, world! <link href="https://github.com/LovelyCatEx/crystal-framework" title="Crystal Framework" />'
  message-channel:
    encryption-key: ${CRYSTAL_MSG_CHANNEL_AES_KEY:TP6qY8C0V7Q6cjlLgkSrPg+/ILT/bXLVmK1+HkBnbk0=}

logging:
  level:
    root: info
    org.flywaydb: info
    org.springframework.security: info
    org.springframework.web: info
    org.springframework.transaction: info
    org.springframework.r2dbc: info
    io.r2dbc.postgresql: info
    org.springframework.boot.actuate: info
    com.lovelycatv.crystalframework.shared.exception: info
server:
  reactive:
    session:
      cookie:
        secure: true
        path: /
        http-only: true
        same-site: none
        domain: ${COOKIE_DOMAIN}
  forward-headers-strategy: framework
  port: ${BACKEND_PORT}
snail-job:
  server:
    host: ${SNAILJOB_SERVER_HOST}
    port: ${SNAILJOB_SERVER_PORT}
  namespace: ${SNAILJOB_NAMESPACE_ID}
  group: ${SNAILJOB_GROUP_NAME}
  token: ${SNAILJOB_GROUP_TOKEN}
